name: covidshield

packages: |
  with (import <nixpkgs> { });
  rubyEnv {
    name = "covidshield";
    ruby = ruby_2_7;
    lockfile = ./Gemfile.lock;
    extra = [ gnumake ];
  }

up:
  - homebrew:
    - protobuf
    - libsodium
    - overmind
  - go:
      version: "1.14"
      tools:
        - github.com/golang/protobuf/protoc-gen-go
        - github.com/golangci/golangci-lint/cmd/golangci-lint
  - railgun

env:
  KEY_CLAIM_TOKEN: thisisaverylongtoken=302
  RETRIEVE_HMAC_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  ECDSA_KEY: 30770201010420a6885a310b694b7bb4ba985459de1e79446dddcd1247c62ece925402b362a110a00a06082a8648ce3d030107a1440342000403eb64f714c4b4ed394331c26c31b7ce7156d00fb28982ad2679a87eaa1a3869802fbeb1d7ee28002762921929c3f7603672d535fcac3d24d57afbb4e2d97f5a
  DATABASE_URL: "root@tcp(covidshield.railgun)/covidshield"
  METRIC_PROVIDER: ""
  TRACER_PROVIDER: ""
  DB_HOST: covidshield.railgun
  DB_USER: root
  DB_PASS: ''


commands:
  server:
    build: true
    run:   overmind start -f ./Procfile.dev
  build:     make
  test: make test
  style: golangci-lint run
  seed: scripts/create-seed-data
  run-built: overmind start -f ./Procfile.dev
