// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RedisConn is an autogenerated mock type for the RedisConn type
type RedisConn struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *RedisConn) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateNonce provides a mock function with given fields:
func (_m *RedisConn) GenerateNonce() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
