package persistence

import "fmt"

// DeviceType the type of the device the event was generated by
type DeviceType string

// Android events generated by Server
// IOS events generated by iPhones
// Server events generated by Server
const (
	Android DeviceType = "Android"
	IOS     DeviceType = "iOS"
	Server  DeviceType = "Server"
)

// IsValid validates the Device Type against a list of allowed strings
func (dt DeviceType) IsValid() error {
	switch dt {
	case Android, IOS, Server:
		{
			return nil
		}
	}
	return fmt.Errorf("invalid Device Type: (%s)", dt)
}
