package persistence

import (
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// Event the event that we are to log
type Event struct {
	Identifier EventType
	DeviceType DeviceType
	Date       time.Time
	Count      int
	Originator string
}

// SaveEvent log an Event in the database
func (c *conn) SaveEvent(event Event) error {

	if err := saveEvent(c.db, event); err != nil {
		return err
	}
	return nil
}

// DeviceType the type of the device the event was generated by
type DeviceType string

// EventType the type of the event that happened
type EventType string

const (
	Android DeviceType = "Android"
	iOS     DeviceType = "iOS"
	Server  DeviceType = "Server"
)

const (
	OTKClaimed   EventType = "OTKClaimed"
	OTKGenerated EventType = "OTKGenerated"
	OTKExpired   EventType = "OTKExpired"
	TEKUploaded  EventType = "TEKUploaded"
)

// IsValid validates the Device Type against a list of allowed strings
func (dt DeviceType) IsValid() error {
	switch dt {
		case Android, iOS, Server:{
			return nil
		}
	}
	return errors.New(fmt.Sprintf("Invalid Device Type: (%s)\n", dt))
}

// IsValid validates the Event Type against a list of allowed strings
func (et EventType) IsValid() error {
	switch et {
	case OTKGenerated, OTKClaimed, OTKExpired, TEKUploaded:
		return nil
	}
	return errors.New(fmt.Sprintf("Invalid EventType: (%s)\n", et))
}


func saveEvent(db *sql.DB, e Event) error {
	if err := e.DeviceType.IsValid(); err != nil {
		return err
	}

	if err := e.Identifier.IsValid(); err != nil {
		return err
	}

	tx, err := db.Begin()
	if err != nil {
		return err
	}

	if _, err := tx.Exec(`
		INSERT INTO events
		(source, identifier, device_type, date, count)
		VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE count = count + ?`,
		e.Originator, e.Identifier, e.DeviceType, e.Date.Format("2006-01-02"), e.Count, e.Count); err != nil {

		if err := tx.Rollback(); err != nil {
			return err
		}
		return err
	}

	if err := tx.Commit(); err != nil {
		return err
	}

	return nil
}
