# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: covidshield.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("covidshield.proto", :syntax => :proto2) do
    add_message "covidshield.KeyClaimRequest" do
      required :oneTimeCode, :string, 1
      required :appPublicKey, :bytes, 2
    end
    add_message "covidshield.KeyClaimResponse" do
      optional :error, :enum, 1, "covidshield.KeyClaimResponse.ErrorCode"
      optional :serverPublicKey, :bytes, 2
    end
    add_enum "covidshield.KeyClaimResponse.ErrorCode" do
      value :NONE, 0
      value :UNKNOWN, 1
      value :INVALID_ONE_TIME_CODE, 2
      value :SERVER_ERROR, 3
      value :INVALID_KEY, 4
    end
    add_message "covidshield.EncryptedUploadRequest" do
      required :serverPublicKey, :bytes, 1
      required :appPublicKey, :bytes, 2
      required :nonce, :bytes, 3
      required :payload, :bytes, 4
    end
    add_message "covidshield.EncryptedUploadResponse" do
      required :error, :enum, 1, "covidshield.EncryptedUploadResponse.ErrorCode"
    end
    add_enum "covidshield.EncryptedUploadResponse.ErrorCode" do
      value :NONE, 0
      value :UNKNOWN, 1
      value :INVALID_KEYPAIR, 2
      value :DECRYPTION_FAILED, 3
      value :INVALID_PAYLOAD, 4
      value :SERVER_ERROR, 5
      value :INVALID_CRYPTO_PARAMETERS, 6
      value :TOO_MANY_KEYS, 7
      value :INVALID_TIMESTAMP, 8
      value :INVALID_ROLLING_PERIOD, 10
      value :INVALID_KEY_DATA, 11
      value :INVALID_ROLLING_START_NUMBER, 12
      value :INVALID_TRANSMISSION_RISK_LEVEL, 13
    end
    add_message "covidshield.Upload" do
      required :timestamp, :message, 1, "google.protobuf.Timestamp"
      repeated :keys, :message, 2, "covidshield.Key"
    end
    add_message "covidshield.File" do
      optional :header, :message, 1, "covidshield.Header"
      repeated :key, :message, 2, "covidshield.Key"
    end
    add_message "covidshield.Header" do
      optional :startTimestamp, :int64, 1
      optional :endTimestamp, :int64, 2
      optional :region, :string, 3
      optional :batchNum, :int32, 4
      optional :batchSize, :int32, 5
    end
    add_message "covidshield.Key" do
      optional :keyData, :bytes, 1
      optional :rollingStartNumber, :uint32, 2
      optional :rollingPeriod, :uint32, 3
      optional :transmissionRiskLevel, :int32, 4
    end
  end
end

module Covidshield
  KeyClaimRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.KeyClaimRequest").msgclass
  KeyClaimResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.KeyClaimResponse").msgclass
  KeyClaimResponse::ErrorCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.KeyClaimResponse.ErrorCode").enummodule
  EncryptedUploadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.EncryptedUploadRequest").msgclass
  EncryptedUploadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.EncryptedUploadResponse").msgclass
  EncryptedUploadResponse::ErrorCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.EncryptedUploadResponse.ErrorCode").enummodule
  Upload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.Upload").msgclass
  File = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.File").msgclass
  Header = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.Header").msgclass
  Key = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("covidshield.Key").msgclass
end
