// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cleanuper is an autogenerated mock type for the Cleanuper type
type Cleanuper struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields:
func (_m *Cleanuper) Cleanup() {
	_m.Called()
}
