// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	tomb "gopkg.in/tomb.v2"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Addr provides a mock function with given fields:
func (_m *Server) Addr() *net.TCPAddr {
	ret := _m.Called()

	var r0 *net.TCPAddr
	if rf, ok := ret.Get(0).(func() *net.TCPAddr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*net.TCPAddr)
		}
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *Server) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Tomb provides a mock function with given fields:
func (_m *Server) Tomb() *tomb.Tomb {
	ret := _m.Called()

	var r0 *tomb.Tomb
	if rf, ok := ret.Get(0).(func() *tomb.Tomb); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tomb.Tomb)
		}
	}

	return r0
}
