name: Deploy to Staging

on:
  push:
    branches: [master]

env:
  GITHUB_SHA: ${{ github.sha }}
  BRANCH: ${{ github.ref }}
  ECS_CLUSTER_NAME: CovidShield

jobs:
  deploy: 
    strategy:
      matrix:
        name : [ retrieval, submission]
        include:
          - name: retrieval
            SERVICE_NAME: KeyRetrieval
            TASK_DEFINITION_FILE: task-defintion-retrieval.json
            LAMBDA: RetrievalValidateBeforeTraffic
            IMAGE_NAME: covid-server/key-retrieval
            APPSPEC_FILE: covidshield-retrieval.json
          - name: submission
            SERVICE_NAME: KeySubmission
            TASK_DEFINITION_FILE: task-defintion-submission.json
            LAMBDA: SubmissionValidateBeforeTraffic
            IMAGE_NAME: covid-server/key-submission
            APPSPEC_FILE: covidshield-submission.json
  
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for container to be built and pushed
        # v1.0.0 of this action as of Jan 28 2021
        uses: fountainhead/action-wait-for-check@4699210ccc66e2a13260803fadbb77085421b891
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-n-push
          ref: ${{ github.sha }}

      - name: Checkout
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        if: steps.wait-for-build.outputs.conclusion == 'success'
        # v1 as of Jan 28 2021
        uses: aws-actions/configure-aws-credentials@51e2d042f8c5cf77f151685c9338e989dc0b8fc8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        if: steps.wait-for-build.outputs.conclusion == 'success'
        id: login-ecr
        # v1 as of Jan 28 2021
        uses: aws-actions/amazon-ecr-login@b9c809dc38d74cd0fde3c13cc4fe4ac72ebecdae

      - name: Download task definition
        if: steps.wait-for-build.outputs.conclusion == 'success'
        id: download-taskdef
        run: |
          aws ecs describe-task-definition --task-definition ${{ matrix.SERVICE_NAME }} --query taskDefinition > ${{ matrix.TASK_DEFINITION_FILE }}
          echo "##[set-output name=container_name;]$(jq -r '.containerDefinitions[0].name' ${{ matrix.TASK_DEFINITION_FILE }})"

      - name: Render image for service
        if: steps.wait-for-build.outputs.conclusion == 'success'
        id: taskdef
        # v1.0.10
        uses: aws-actions/amazon-ecs-render-task-definition@9666dc9d3bf790a3a6a49737b240f17fa599a5f2
        with:
          task-definition: ${{ matrix.TASK_DEFINITION_FILE }}
          container-name: ${{ steps.download-taskdef.outputs.container_name }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.IMAGE_NAME }}:${{ github.sha }}

      - name: Render appspec for service
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
          CONTAINER_PORT=`jq '.containerDefinitions[0].portMappings[0].containerPort' ${{ matrix.TASK_DEFINITION_FILE }}`
          CONTAINER_NAME=${{ steps.download-taskdef.outputs.container_name }}
          TASKDEF_ARN=`jq -r '.taskDefinitionArn' ${{ matrix.TASK_DEFINITION_FILE }} | cut -f 1-6 -d "/"`
          jq  --argjson port "$CONTAINER_PORT" --arg cname "$CONTAINER_NAME" --arg taskdefarn "$TASKDEF_ARN" --arg lambda "${{ matrix.LAMBDA }}" '.Resources[0].TargetService.Properties.TaskDefinition = $taskdefarn | .Resources[0].TargetService.Properties.LoadBalancerInfo.ContainerName = $cname | .Resources[0].TargetService.Properties.LoadBalancerInfo.ContainerPort = $port | .Hooks[0].BeforeAllowTraffic = $lambda ' config/infrastructure/aws/appspec-template.json > ${{ matrix.APPSPEC_FILE }}

      - name: Deploy image for service
        if: steps.wait-for-build.outputs.conclusion == 'success'
        timeout-minutes: 10
        # v1.4.2
        uses: aws-actions/amazon-ecs-deploy-task-definition@c74a8ca2cd0dd04d25f469715e23cb6c2fe0f01a
        with:
          task-definition: ${{ steps.taskdef.outputs.task-definition }}
          service: ${{ matrix.SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
          codedeploy-appspec: ${{ github.workspace }}/${{ matrix.APPSPEC_FILE }}

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
