name: Shellcheck
on:
  push:
    paths:
      - "**/*.sh"
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: |
        ./bin/run-shellcheck.sh
