name: Shellcheck
on: push
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: |
        shellcheck --version
        ./bin/run-shellcheck.sh
