name: Snyk integration
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # pin@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@d9ca26550c26e3cbbbdde59ee4ace0a2f385897c # pin@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=go.mod --org=cds-snc --project-name=covid-alert-server
